version: '3.9'

# Production docker-compose that uses pre-built images from GitHub Container Registry
# Usage: docker-compose -f docker-compose.production.yml up -d

services:
  linkedin-scraper-api:
    # Use the pre-built image from GitHub Container Registry
    # Replace 'YOUR_USERNAME' with your actual GitHub username
    image: ghcr.io/YOUR_USERNAME/n8n_linkedinjobscrapper:latest
    
    container_name: linkedin-scraper-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Server configuration
      PORT: "8000"
      HOST: "0.0.0.0"
      
      # LinkedIn Authentication (set these in your .env file)
      LINKEDIN_EMAIL: ${LINKEDIN_EMAIL}
      LINKEDIN_PASSWORD: ${LINKEDIN_PASSWORD}
      LINKEDIN_LI_AT: ${LINKEDIN_LI_AT:-}
      LINKEDIN_JSESSIONID: ${LINKEDIN_JSESSIONID:-}
      LINKEDIN_LIAP: ${LINKEDIN_LIAP:-}
      LINKEDIN_LIDC: ${LINKEDIN_LIDC:-}
      LINKEDIN_BCOOKIE: ${LINKEDIN_BCOOKIE:-}
      LINKEDIN_BSCOOKIE: ${LINKEDIN_BSCOOKIE:-}
      
      # Debug mode
      DEBUG_MODE: ${DEBUG_MODE:-false}
    volumes:
      # Mount .env file for credentials (read-only)
      - ./.env:/app/.env:ro
      # Mount config.json for search configuration
      - ./config.json:/app/config.json:ro
    networks:
      - linkedin-scraper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  linkedin-scraper-network:
    driver: bridge 